import React, { useState, useEffect } from "react";

const RandomQuote = () => {
  const quotes = [
    "Believe in your potential; your career is a journey of endless possibilities.",
    "Every effort brings you closer to success; let your career shine.",
    "Dream big and act now; your career can achieve greatness.",
    "In every step, find the strength to advance your career.",
    "Your career is the path to your dreams; pursue it with passion.",
    "Each day is a new opportunity to grow in your career.",
    "Success is built on hard work; let your career be the proof.",
    "With dedication and vision, your career can reach new heights.",
    "Your career is a journey of continuous improvement and success.",
    "Believe in your dreams; let your career be the realization.",
    "Every moment is a chance to excel in your career.",
    "The future is bright; let your career be the pathway.",
    "With every step, you pave the way for a successful career.",
    "Your career is a journey of discovery and achievement.",
    "Let your passion drive you; your career is the journey to success.",
    "Embrace challenges; your career is a testament to your resilience.",
    "Every effort counts; let your career be the path to your dreams.",
    "With dedication, your career can lead you to extraordinary achievements.",
    "In every step forward, leave fear behind in your career.",
    "Your career is the bridge to your dreams; cross it with confidence.",
    "Embrace each day with optimism; your career is the gateway to possibilities.",
    "Let your vision guide you; your career is the journey to realizing potential.",
    "Success is within reach; let your career be the bridge to achievements.",
    "Every step forward is progress; let your career be a journey of improvement.",
    "Your career is a story of growth; write each chapter with purpose.",
    "Believe in yourself; let your career be the path to future achievements.",
    "Every moment is a chance to shine in your career.",
    "With each effort, build a legacy in your career.",
    "Your future is shaped by your actions today; let your career be the path.",
    "With passion and persistence, your career can reach new heights.",
    "In every challenge, find the opportunity to advance your career.",
    "Success is built on dreams and action; let your career be the realization.",
    "Each day is a new opportunity to advance your career.",
    "Believe in your potential; your career is the journey to a brighter future.",
    "Every effort brings you closer to your career goals.",
    "Your career is the pathway to realizing your dreams.",
    "In every step, find the strength to grow in your career.",
    "With dedication and vision, your career can achieve greatness.",
    "Embrace each day with optimism; your career is the path to success.",
    "Your career is a journey of continuous improvement.",
    "Success is within reach; let your career be the path to achievements.",
    "Every moment is a chance to excel in your career.",
    "With every step forward, leave doubt behind in your career.",
    "Believe in your dreams; let your career be the journey to realization.",
    "With dedication, your career can lead to extraordinary achievements.",
    "Every effort counts; let your career be the path to success.",
    "In every challenge, find the opportunity to grow your career.",
    "Your career is the bridge to your dreams; cross it with determination.",
    "Each day is a new opportunity to shine in your career.",
    "Believe in your potential; your career is the journey to success.",
    "Every step forward is progress; let your career be a journey of growth.",
    "In every step, find the strength to advance in your career.",
    "With dedication and vision, your career can reach new heights.",
    "Your career is a journey of discovery and achievement.",
    "Embrace challenges; your career is a testament to your resilience.",
    "Every effort brings you closer to success in your career.",
    "Your future is shaped by your actions today; let your career be the path.",
    "With passion and persistence, your career can reach new heights.",
    "In every step forward, leave fear behind in your career.",
    "Believe in your dreams; let your career be the realization.",
    "Each day is a new opportunity to advance your career.",
    "Success is built on dreams and action; let your career be the realization.",
    "With dedication, your career can lead you to extraordinary achievements.",
    "Your career is the pathway to realizing your dreams.",
    "Every effort counts; let your career be the path to success.",
    "In every challenge, find the opportunity to grow in your career.",
    "With passion and persistence, your career can achieve greatness.",
    "Your career is a journey of continuous improvement.",
    "Every moment is a chance to excel in your career.",
    "Believe in your potential; your career is the journey to success.",
    "In every step, find the strength to advance in your career.",
    "With dedication and vision, your career can reach new heights.",
    "Your career is a journey of discovery and achievement.",
    "Embrace challenges; your career is a testament to your resilience.",
    "Every effort brings you closer to success in your career.",
    "Your future is shaped by your actions today; let your career be the path.",
    "With passion and persistence, your career can reach new heights.",
    "In every step forward, leave fear behind in your career.",
    "Believe in your dreams; let your career be the realization.",
    "Each day is a new opportunity to advance your career.",
    "Success is built on dreams and action; let your career be the realization.",
    "With dedication, your career can lead you to extraordinary achievements.",
    "Your career is the pathway to realizing your dreams.",
    "Every effort counts; let your career be the path to success.",
    "In every challenge, find the opportunity to grow in your career.",
    "With passion and persistence, your career can achieve greatness.",
    "Your career is a journey of continuous improvement.",
    "Every moment is a chance to excel in your career.",
  ];

  const [currentQuoteIndex, setCurrentQuoteIndex] = useState(0);

  useEffect(() => {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    setCurrentQuoteIndex(randomIndex);
  }, []);

  return <p>{quotes[currentQuoteIndex]}</p>;
};

export default RandomQuote;
